"""Configuration management for NewsDigest."""

from newsdigest.config.environments import (
    Environment,
    apply_env_file,
    detect_environment,
    get_config_path,
    get_env_file_path,
    get_environment_info,
    is_development,
    is_production,
    is_staging,
    is_test,
    load_config,
    load_env_file,
)
from newsdigest.config.secrets import (
    AWSSecretsManager,
    EnvLoader,
    SecretMasker,
    SecretsManager,
    SecretValue,
    get_env,
    get_env_loader,
    get_secret,
    get_secret_masker,
    init_env,
    mask_secrets,
    register_secret,
)
from newsdigest.config.settings import Config


__all__ = [
    "AWSSecretsManager",
    "Config",
    "EnvLoader",
    "Environment",
    "SecretMasker",
    "SecretValue",
    "SecretsManager",
    "apply_env_file",
    "detect_environment",
    "get_config_path",
    "get_env",
    "get_env_file_path",
    "get_env_loader",
    "get_environment_info",
    "get_secret",
    "get_secret_masker",
    "init_env",
    "is_development",
    "is_production",
    "is_staging",
    "is_test",
    "load_config",
    "load_env_file",
    "mask_secrets",
    "register_secret",
]
